import point.point_exceptions
from point.point import Point
